# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605a0d7952d3b72959e712799012ad7cd2ecacca2249fa2c5076cc84d0cc860e9457c061512318042b97b02f41a2151eb5ecaf955472b7c727052203851bc687

test:
  secret_key_base: a264dae361829c11951bd0552fc645769f1894b868bda850b8c053c9f26b0db0d14214a390734dd22f28c4d74befa7a86783ab50bc53c395434c8faaaa084669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
